import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Select } from "./components/select";
import styles from "../styles/Home.module.css";

const TITLE = "Visualizador de Divisas";

const Home: NextPage = () => {
  const [state, setState] = useState<number>(0);
  return (
    <div className={styles.container}>
      <Head>
        <title>{TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>{TITLE}</h1>

      <Select
        name="Divisas"
        items={[
          { label: "sada", value: 1 },
          { label: "sadsa", value: 2 },
        ]}
        setState={setState}
      />
    </div>
  );
};

export default Home;
