import type { NextPage } from "next";
import type { Division, Prices, Options, TotalDivision } from "../types";
import { useState, useEffect } from "react";
import Head from "next/head";
import { Select } from "./components/select";
import { Divisas } from "./components/divisas";
import styles from "../styles/Home.module.css";
import { client, initial } from "../common";

const TITLE = "Visualizador de Precios GNT";

const Home: NextPage = () => {
  const [list, setList] = useState<Options[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [state, setState] = useState<TotalDivision>(initial);

  const handleSelectChange = (value: string) => setSelected(value);

  useEffect(() => {
    client.onopen = () => {
      console.log("Connection has been opened!");
      client.send("prices");
    };
    client.onmessage = (message) => {
      const data: Prices = JSON.parse(message.data as any)?.prices as Prices;

      //Se carga la lista de todas las divisas disponibles para cargarlo en el select
      if (list.length === 0)
        setList(
          Object.keys(data).map((x) => ({
            label: x,
            value: x,
          }))
        );

      //Verifica si un elemento de la lista haya sido seleccionado y a partir de la seleccion mostraran los respectivos valores
      if (selected !== null) {
        const content: Division = data[selected];
        if (content) {
          setState((prev) => ({
            ask: content.ask,
            bid: content.bid,
            divisa: content.divisa,
            prevAsk: prev.ask,
            prevBid: prev.bid,
          }));
        }
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selected]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>{TITLE}</h1>

      <Select
        name="Divisas"
        items={list}
        defaultValue="Selecciona tu divisa"
        onChange={handleSelectChange}
      />

      <Divisas values={state} />
    </div>
  );
};

export default Home;
