import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Select } from "./components/select";
import { Divisas } from './components/divisas';
import styles from "../styles/Home.module.css";
import { client } from '../common';

const TITLE = "Visualizador de Divisas";

const Home: NextPage = () => {
  const [state, setState] = useState<any>(0);


  const handleSelectChange = (value: string) => {
    client.send("prices");
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>{TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>{TITLE}</h1>

      <Select
        name="Divisas"
        items={[
          { label: "sada", value: 1 },
          { label: "sadsa", value: 2 },
        ]}
        setState={setState}
        defaultValue="Selecciona tu divisa"
        onChange={handleSelectChange}
      />

      <Divisas value={state} />

    </div>
  );
};

export default Home;
